# Caso de estudio: Análisis de sentimiento

En este ejercicio se usará la librería sklearn con el fin de evaluar los modelos creados en el bloque 3 para predecir el sentimiento de las opiniones del dataset: positivo o negativo.

Se deberá partir de los modelos creados en el bloque *Modelos de predicción de la emoción*. Para ello, puedes incorporar el código de la actividad anterior (preguntas 1 a 6) antes de comenzar con la resolución de las preguntas de este bloque.

In [1]:
#Incorporamos el codigo del Bloque 3
import pandas as pd
import numpy as np
file_path = './Amazon_Unlocked_Mobile.csv' #Ponemos este fichero en la carpeta del Bloque 4 tambien
df = pd.read_csv(file_path) 
df = df.sample(frac=0.1, random_state=10)
df.dropna(inplace=True)
df2=df.drop(df[df.Rating == 3].index)
df2.loc[df2['Rating'] < 3, 'Sentimiento'] = 0 
df2.loc[df2['Rating'] > 3, 'Sentimiento'] = 1
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df2[['Product Name','Brand Name','Price',
                                                         'Rating','Reviews','Review Votes']],df2['Sentimiento'],test_size=0.3)
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
x_train_matrix = vectorizer.fit_transform(x_train['Reviews'])
x_test_matrix = vectorizer.transform(x_test['Reviews'])

#Modelo Naive Bayes
from sklearn.naive_bayes import MultinomialNB
clfrNB = MultinomialNB()
clfrNB.fit(x_train_matrix, y_train)
predicted_labels = clfrNB.predict(x_test_matrix.toarray())

#Modelo Logistic Regression
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(x_train_matrix, y_train)
predicted_labels2 = classifier.predict(x_test_matrix.toarray())

#Modelo SVM
from sklearn import svm
clfrSVM = svm.SVC(kernel='linear', C=0.1)
clfrSVM.fit(x_train_matrix, y_train)
predicted_labels3 = clfrSVM.predict(x_test_matrix.toarray())

C:\Users\inima\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


## Pregunta 1
### Matriz de confusión de los modelos de clasificación (2,25 puntos)

Debes mostrar por pantalla la matriz de confusión de los modelos de los modelos de Naive Bayes, Regresión logística y SVM utilizados en el cuaderno de prácticas del bloque tres. 

*Debes evaluar los modelos utilizados en las preguntas 4, 5 y 6 del cuaderno de prácticas del bloque 3*

In [4]:
from sklearn.metrics import confusion_matrix
#Para estas cosas, empleamos las comparaciones del y_test con las predicted labels de cada modelo.
#Predicted labels1 corresponde a Naive Vayes, Predicted labels2 corresponde a Regresion Logistica y Predicted labels3
#corresponde a SVM.
print('Matriz de confusión Naive bayes: ')
print(confusion_matrix(y_test, predicted_labels))
print('Matriz de confusión Regresión logística: ')
print(confusion_matrix(y_test, predicted_labels2))
print('Matriz de confusión SVM: ')
print(confusion_matrix(y_test, predicted_labels3))

Matriz de confusión Naive bayes: 
[[1814  520]
 [ 232 6656]]
Matriz de confusión Regresión logística: 
[[1906  428]
 [ 226 6662]]
Matriz de confusión SVM: 
[[1882  452]
 [ 224 6664]]


## Pregunta 2
### Tasa de acierto de los modelos de clasificación (2,25 puntos)

A continuación debes calcular la tasa de acierto de los modelos de Naive Bayes, Regresión logística y SVM utilizados en el cuaderno de prácticas del bloque tres. 

*Debes evaluar los modelos utilizados en las preguntas 4, 5 y 6 del cuaderno de prácticas del bloque 3*

In [5]:
from sklearn.metrics import accuracy_score
#Para estas cosas, empleamos las comparaciones del y_test con las predicted labels de cada modelo.
#Predicted labels1 corresponde a Naive Vayes, Predicted labels2 corresponde a Regresion Logistica y Predicted labels3
#corresponde a SVM.
print('AUC Naive bayes: ')
print(accuracy_score(y_test,predicted_labels))
print('AUC Regresión Logística: ')
print(accuracy_score(y_test,predicted_labels2))
print('AUC SVM: ')
print(accuracy_score(y_test,predicted_labels3))

AUC Naive bayes: 
0.9184558664064194
AUC Regresión Logística: 
0.9290826284970722
AUC SVM: 
0.9266970288440686


## Pregunta 3 
### Métricas precision, recall y f1-score de los modelos (2,25 puntos)

Calcula las métricas precision, recall y f1-score de los modelos de Naive Bayes, Regresión logística y SVM utilizados en el cuaderno de prácticas del bloque tres. 

*Debes evaluar los modelos utilizados en las preguntas 4, 5 y 6 del cuaderno de prácticas del bloque 3*

In [6]:
from sklearn.metrics import f1_score
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score


print('\tPrecision NB;' )
print(precision_score(y_test,predicted_labels))
print('\tRecall NB:' )
print(recall_score(y_test,predicted_labels))
print('\tF1 score micro NB: ' )
print(f1_score(y_test,predicted_labels))

print('\tPrecision RL:')
print(precision_score(y_test,predicted_labels2))
print('\tRecall RL:' )
print(recall_score(y_test,predicted_labels2))
print('\tF1 score micro RL:' )
print(f1_score(y_test,predicted_labels2))

print('\tPrecision SVM;' )
print(precision_score(y_test,predicted_labels3))
print('\tRecall SVM:' )
print(precision_score(y_test,predicted_labels3))
print('\tF1 score micro SVM:' )
print(precision_score(y_test,predicted_labels3))

	Precision NB;
0.927536231884058
	Recall NB:
0.9663182346109176
	F1 score micro NB: 
0.9465301478953356
	Precision RL:
0.9396332863187589
	Recall RL:
0.9671893147502904
	F1 score micro RL:
0.9532121905852053
	Precision SVM;
0.9364811691961776
	Recall SVM:
0.9364811691961776
	F1 score micro SVM:
0.9364811691961776


## Pregunta 4 
### Selección del modelo más óptimo (1 punto)

Atendiendo a las métricas obtenidas para cada uno de los modelos, indica cuál es el modelo que utilizarías para predecir el sentimiento de las opiniones en un sistema en producción. Por favor, justifica tu respuesta.

In [7]:
print('El modelo seleccionado es:')
print('Todos los modelos ofrecen resultados bastante buenos y similares. Sin embargo, la REGRESION LOGISTICA es un poco mejor')
print('que el resto:')
print('- Ofrece la tasa de acierto, precision, F1 score y Recall mas elevados.')
print('- En la matriz de confusion, es el modelo que mas Verdadero Positivos y Verdadero Negativos ofrece, minimizando asi')
print('la cantidad de Falsos Negativos y Falsos Positivos, que son errores.')

El modelo seleccionado es:
Todos los modelos ofrecen resultados bastante buenos y similares. Sin embargo, la REGRESION LOGISTICA es un poco mejor
que el resto:
- Ofrece la tasa de acierto, precision, F1 score y Recall mas elevados.
- En la matriz de confusion, es el modelo que mas Verdadero Positivos y Verdadero Negativos ofrece, minimizando asi
la cantidad de Falsos Negativos y Falsos Positivos, que son errores.


## Pregunta 5 
### Aplicación de validación cruzada (2,25 puntos)


Realiza una validación cruzada sobre el conjunto de entrenamiento de 5 iteracciones y muestra un array con las evaluaciones obtenidas para cada partición en los modelos de Naive Bayes, Regresión logística y SVM utilizados en el cuaderno de prácticas del bloque tres.

In [8]:

from sklearn.model_selection import cross_val_score

print('scores NB:')
print(cross_val_score(clfrNB,x_train_matrix, y_train, cv=5))
print('scores RL:')
print(cross_val_score(classifier,x_train_matrix, y_train, cv=5))
print('scores SVM:')
print(cross_val_score(clfrSVM,x_train_matrix, y_train, cv=5))

scores NB:
[0.92284453 0.91308389 0.92005578 0.91703463 0.9186614 ]
scores RL:


C:\Users\inima\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\inima\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

[0.92865443 0.92865443 0.92516849 0.92981641 0.93562631]
scores SVM:
[0.92702766 0.92261213 0.92540088 0.9247037  0.93237276]


Ese seria el fin del ejercicio 4.